In [ ]:
data = """ About the Program
What is the fee for the Full Stack Web Development Bootcamp?
The bootcamp follows a monthly subscription model where you pay Rs 999/month.
What is the total duration of the bootcamp?
The total duration of the bootcamp is 6 months, so the total fee becomes 999*6 = Rs 6000 (approx).
What is the syllabus of the bootcamp?
We cover the following modules:
HTML & CSS
JavaScript (Basic to Advanced)
Version Control with Git & GitHub
React.js
Node.js & Express
MongoDB & SQL
REST APIs
Authentication & Authorization
Deployment using Vercel & AWS
You can check the detailed syllabus here - https://example.com/fullstack-syllabus
Will DevOps or CI/CD be covered in this bootcamp?
Only introductory topics will be covered; the main focus is on MERN stack development.
What if I miss a live session? Will I get a recording?
Yes, all sessions are recorded and uploaded to your dashboard.
Where can I find the class schedule?
Check the official schedule sheet here - https://example.com/schedule
What is the average duration of a live session?
Approximately 2.5 hours per session.
What is the mode of instruction?
Hinglish (mix of Hindi and English)
How will I be informed about the upcoming class?
You will get an email and WhatsApp reminder before each session.
Can I join the course if I have no technical background?
Yes, the bootcamp is beginner-friendly.
Is it possible to join in the middle of the bootcamp?
Absolutely. Once you join, all past sessions will be unlocked.
Do I need to submit assignments?
No need to submit. Solutions will be provided for self-evaluation.
Will we build real projects in the course?
Yes, each module includes a capstone project.
Where can I contact for general support?
You can write to support@webcamp.in
Payment/Registration Questions
Where should I make my payments?
All payments must be done on our official website - https://example.com
Can I pay the full fee in one go?
No, the bootcamp follows a monthly subscription model only.
What is the validity of each monthly payment?
30 days from the date of payment.
Is there a refund policy?
Yes, we offer a 5-day refund policy from the day of payment.
I live outside India and can’t make a payment, what should I do?
Please write to us at support@webcamp.in for international payment options.
Post Registration Queries
How long will I have access to paid content?
Till your subscription is active. After completing all 6 payments, access is extended till Dec 2025.
Why is lifetime access not provided?
Due to the low course fee, we can’t offer lifetime access.
How can I clear doubts?
Submit the doubt form available in your dashboard to schedule a 1-on-1 session.
Can I ask doubts from earlier sessions if I join late?
Yes, just select the correct session/week in the doubt form.
Certificate & Placement Assistance
What is the criteria to get the certificate?
1. Complete payment (Rs 6000 total)
2. Attempt at least 80% of the assignments
What does placement assistance include?
Portfolio building
Mock interviews
Resume review
Referral network access
Job hunting strategy sessions
Does it guarantee a job or interview?
No, we do not guarantee placements or interviews. Assistance is provided, not assurance."""

In [ ]:
pip install Tokenizer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.8/112.8 kB 4.0 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokanizer = Tokenizer()

In [ ]:
tokanizer.fit_on_texts([data])

In [ ]:
tokanizer.word_index

{'the': 1,
 'is': 2,
 'i': 3,
 'a': 4,
 'of': 5,
 'to': 6,
 'what': 7,
 'bootcamp': 8,
 'will': 9,
 'can': 10,
 'in': 11,
 'payment': 12,
 'be': 13,
 'session': 14,
 'you': 15,
 'we': 16,
 'yes': 17,
 'access': 18,
 'fee': 19,
 'for': 20,
 'where': 21,
 'total': 22,
 'all': 23,
 'sessions': 24,
 'and': 25,
 'schedule': 26,
 'join': 27,
 'no': 28,
 'monthly': 29,
 'subscription': 30,
 'rs': 31,
 'duration': 32,
 '6': 33,
 'syllabus': 34,
 'https': 35,
 'example': 36,
 'com': 37,
 'or': 38,
 'on': 39,
 'if': 40,
 'live': 41,
 'get': 42,
 'your': 43,
 'how': 44,
 'each': 45,
 'course': 46,
 'do': 47,
 'submit': 48,
 'provided': 49,
 'support': 50,
 'payments': 51,
 'from': 52,
 'not': 53,
 '1': 54,
 'assistance': 55,
 'about': 56,
 'full': 57,
 'stack': 58,
 'development': 59,
 'follows': 60,
 'model': 61,
 'pay': 62,
 '999': 63,
 '6000': 64,
 'js': 65,
 'check': 66,
 'here': 67,
 'covered': 68,
 'only': 69,
 'dashboard': 70,
 'class': 71,
 'official': 72,
 '2': 73,
 '5': 74,
 'have': 75,

In [ ]:
for sentence in data.split('\n'):
  print(sentence)

 About the Program
What is the fee for the Full Stack Web Development Bootcamp?
The bootcamp follows a monthly subscription model where you pay Rs 999/month.
What is the total duration of the bootcamp?
The total duration of the bootcamp is 6 months, so the total fee becomes 999*6 = Rs 6000 (approx).
What is the syllabus of the bootcamp?
We cover the following modules:
HTML & CSS
JavaScript (Basic to Advanced)
Version Control with Git & GitHub
React.js
Node.js & Express
MongoDB & SQL
REST APIs
Authentication & Authorization
Deployment using Vercel & AWS
You can check the detailed syllabus here - https://example.com/fullstack-syllabus
Will DevOps or CI/CD be covered in this bootcamp?
Only introductory topics will be covered; the main focus is on MERN stack development.
What if I miss a live session? Will I get a recording?
Yes, all sessions are recorded and uploaded to your dashboard.
Where can I find the class schedule?
Check the official schedule sheet here - https://example.com/schedu

In [ ]:
input_seq = []

for sentence in data.split('\n'):
  tokanized_sentence = tokanizer.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokanized_sentence)):
    n_gram_seq = tokanized_sentence[:i+1]
    input_seq.append(n_gram_seq)


In [ ]:
input_seq

[[56, 1],
 [56, 1, 101],
 [7, 2],
 [7, 2, 1],
 [7, 2, 1, 19],
 [7, 2, 1, 19, 20],
 [7, 2, 1, 19, 20, 1],
 [7, 2, 1, 19, 20, 1, 57],
 [7, 2, 1, 19, 20, 1, 57, 58],
 [7, 2, 1, 19, 20, 1, 57, 58, 102],
 [7, 2, 1, 19, 20, 1, 57, 58, 102, 59],
 [7, 2, 1, 19, 20, 1, 57, 58, 102, 59, 8],
 [1, 8],
 [1, 8, 60],
 [1, 8, 60, 4],
 [1, 8, 60, 4, 29],
 [1, 8, 60, 4, 29, 30],
 [1, 8, 60, 4, 29, 30, 61],
 [1, 8, 60, 4, 29, 30, 61, 21],
 [1, 8, 60, 4, 29, 30, 61, 21, 15],
 [1, 8, 60, 4, 29, 30, 61, 21, 15, 62],
 [1, 8, 60, 4, 29, 30, 61, 21, 15, 62, 31],
 [1, 8, 60, 4, 29, 30, 61, 21, 15, 62, 31, 63],
 [1, 8, 60, 4, 29, 30, 61, 21, 15, 62, 31, 63, 103],
 [7, 2],
 [7, 2, 1],
 [7, 2, 1, 22],
 [7, 2, 1, 22, 32],
 [7, 2, 1, 22, 32, 5],
 [7, 2, 1, 22, 32, 5, 1],
 [7, 2, 1, 22, 32, 5, 1, 8],
 [1, 22],
 [1, 22, 32],
 [1, 22, 32, 5],
 [1, 22, 32, 5, 1],
 [1, 22, 32, 5, 1, 8],
 [1, 22, 32, 5, 1, 8, 2],
 [1, 22, 32, 5, 1, 8, 2, 33],
 [1, 22, 32, 5, 1, 8, 2, 33, 104],
 [1, 22, 32, 5, 1, 8, 2, 33, 104, 105],
 [1, 

In [ ]:
max_length = max([len(x) for x in input_seq])

In [ ]:
max_length

19

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_seq = pad_sequences(input_seq, maxlen=max_length, padding='pre')
display(padded_input_seq)

array([[  0,   0,   0, ...,   0,  56,   1],
       [  0,   0,   0, ...,  56,   1, 101],
       [  0,   0,   0, ...,   0,   7,   2],
       ...,
       [  0,   0,   0, ...,  55,   2,  49],
       [  0,   0,   0, ...,   2,  49,  53],
       [  0,   0,   0, ...,  49,  53, 250]], dtype=int32)

In [ ]:
X = padded_input_seq[:, :-1]
y = padded_input_seq[:, -1]

In [ ]:
print(X)

[[ 0  0  0 ...  0  0 56]
 [ 0  0  0 ...  0 56  1]
 [ 0  0  0 ...  0  0  7]
 ...
 [ 0  0  0 ... 98 55  2]
 [ 0  0  0 ... 55  2 49]
 [ 0  0  0 ...  2 49 53]]


In [ ]:
print(y)

[  1 101   2   1  19  20   1  57  58 102  59   8   8  60   4  29  30  61
  21  15  62  31  63 103   2   1  22  32   5   1   8  22  32   5   1   8
   2  33 104 105   1  22  19 106  63  33  31  64 107   2   1  34   5   1
   8 108   1 109 110 112 114   6 115 117 118 119 120  65  65 123 125 127
 129 131 132 133  10  66   1 134  34  67  35  36  37 135  34 136  38 137
 138  13  68  11 139   8 140 141   9  13  68   1 142 143   2  39 144  58
  59  40   3 145   4  41  14   9   3  42   4 146  23  24 147 148  25 149
   6  43  70  10   3 150   1  71  26   1  72  26 151  67  35  36  37  26
   2   1 152  32   5   4  41  14  73  74 154 155  14   2   1 156   5 157
 159   5 160  25 161   9   3  13 162  56   1 163  71   9  42 164 165  25
 166 167 168  45  14   3  27   1  46  40   3  75  28 169 170   1   8   2
 171 172  76 173   6  27  11   1 174   5   1   8 176  15  27  23 177  24
   9  13 178   3  77   6  48  78  77   6  48 179   9  13  49  20 180 181
  16 182 183 184  11   1  46  45 185 186   4 187 18

In [ ]:
 X.shape

(474, 18)

In [ ]:
y.shape

(474,)

In [ ]:
len(tokanizer.word_index)

250

In [ ]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes=len(tokanizer.word_index)+1)

In [ ]:
y.shape

(474, 251)

In [ ]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()

model.add(Embedding(251, 100, input_length=19))
model.add(LSTM(150))
model.add(Dense(251, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.0445 - loss: 5.5113
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.0724 - loss: 5.1857
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.0839 - loss: 5.0107
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.0832 - loss: 4.9568
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.0680 - loss: 4.9901
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.0801 - loss: 4.9032
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.0817 - loss: 4.7929
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.0917 - loss: 4.6941
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.1129 - loss: 4.5675
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.0951 - loss: 4.5790
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0963 - loss: 4.4217
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step

In [ ]:
import time
text = "We cover"

for i in range(10):
  # tokenize
  token_text = tokanizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokanizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
We cover the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
We cover the following
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
We cover the following modules
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
We cover the following modules modules
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
We cover the following modules modules modules
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
We cover the following modules modules modules in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
We cover the following modules modules modules in in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
We cover the following modules modules modules in in the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
We cover the following modules modules modules in in the doubt
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
We cover the following modules modules modules in in the doubt form
